version: "3.8"

services:
  postgres_pachinko:
    container_name: postgres_pachinko
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      #   - ./postgres_data:/var/lib/postgresql/data
      - ./back/db_files/db_tables_setup.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    networks:
      - app-network

  pgadmin_pachinko:
    container_name: pgadmin_pachinko
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - .env
    ports:
      - "8888:88"
    # volumes:
    #   - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres_pachinko
    networks:
      - app-network

  redisdb_pachinko:
    container_name: redisdb_pachinko
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - "6380:6379"
    networks:
      - app-network

# volumes:
#     db-data:
#     pgadmin-data:
networks:
  app-network:
    driver: bridge
